2022-12-02 01:35:46,147 INFO    MainThread:66582 [wandb_setup.py:_flush():76] Loading settings from /Users/keanl/.config/wandb/settings
2022-12-02 01:35:46,147 INFO    MainThread:66582 [wandb_setup.py:_flush():76] Loading settings from /Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/wandb/settings
2022-12-02 01:35:46,147 INFO    MainThread:66582 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_unet_classifier.py', 'program': '/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_unet_classifier.py'}
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_init.py:_log_setup():428] Logging user logs to /Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/wandb/run-20221202_013546-1xfdlyvz/logs/debug.log
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/wandb/run-20221202_013546-1xfdlyvz/logs/debug-internal.log
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_init.py:init():462] calling init triggers
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'dataset': 'retina', 'validation_split': 'validation', 'epochs': 20, 'batch_size': 32, 'lr': 0.001, 'activation': 'relu', 'dropout': None, 'max_observed_percentage': 0.5, 'min_observed_percentage': 0.05}
2022-12-02 01:35:46,148 INFO    MainThread:66582 [wandb_init.py:init():510] wandb.init() called when a run is still active
2022-12-02 01:36:00,369 INFO    MainThread:66582 [wandb_run.py:_config_callback():1136] config_cb None None {'dataset': 'retina', 'epochs': '20'}
2022-12-02 01:39:53,109 INFO    MainThread:66582 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 1
2022-12-02 01:39:53,325 INFO    MainThread:66582 [wandb_run.py:_restore():1839] restore
